### ISSUE TITLE
TGMacro Bug

### ISSUE THREAD

**Issue by itsthaboikso** [trksyln/TGMacro#1]
When I download TGMacro and try to open it with WinRaR It opens for a few seconds and then closes then when I try again It doesn't open plz help.

**Comment by trksyln** [comment]
Hey there!

Im guessing you downloading the released version not the source code?

Released version flagged as virus by many antivirusus (false positives). This is why i also publish the source code to show/prove im not doing anything harmful with the software.

So.. you can download the source code and build yourself or you can disable your antivirus software and retry downloading the release.
