### ISSUE TITLE
already running issue

### ISSUE THREAD

**Issue by amayathebest** [trksyln/TGMacro#5]
hey, whenever i try to open TGMacro is keeps saying "TGM already running" and its nowhere to be found! then when i try to delete it says "error. windows cannot delete this app due to it being open and running" i have been trying for days and still not working. please help!

**Comment by trksyln** [comment]
Hey! 
If you using multiple accounts on windows it might be open on another account. Open task manager then go details tab. There must be a check box to show all acounts processes after checking thah you should be able to see TGMacro.exe on details tab and kill the process.
