### ISSUE TITLE
tgmacro

### ISSUE THREAD

**Issue by ha812** [trksyln/TGMacro#8]
i do0nwloaded the correct tgmacro file (tgmacro.exe) but when i click open it does not pop up and my clipchamp doesnt open also+

**Comment by trksyln** [comment]
Hello;
There no exe file here, just the source code. 
Where did you download tgmacro.exe? and what you mean by clipchamp?

**Comment by ha812** [comment]
i downloaded tgmacro.exe on sourcenet.com and clipchamp is the app on my computer to edit videos.

**Comment by ha812** [comment]
sourceforge.net*

**Comment by trksyln** [comment]
Please me more specific
